[2020-12-09 15:45:11,981] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-09T10:10:00+00:00 [queued]>
[2020-12-09 15:45:11,991] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-09T10:10:00+00:00 [queued]>
[2020-12-09 15:45:11,991] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 15:45:11,991] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-09 15:45:11,991] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 15:45:11,996] {taskinstance.py:901} INFO - Executing <Task(PostgresOperator): create_table> on 2020-12-09T10:10:00+00:00
[2020-12-09 15:45:11,999] {standard_task_runner.py:54} INFO - Started process 56854 to run task
[2020-12-09 15:45:12,042] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_PG', 'create_table', '2020-12-09T10:10:00+00:00', '--job_id', '569', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/FileSensorDemo.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmprw3athdu']
[2020-12-09 15:45:12,043] {standard_task_runner.py:78} INFO - Job 569: Subtask create_table
[2020-12-09 15:45:12,078] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_PG.create_table 2020-12-09T10:10:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-09 15:45:12,099] {postgres_operator.py:62} INFO - Executing: CREATE TABLE sampletable(
            Date text,
            Open text,
            High text,
            Low text,
            Close text
        );
        
[2020-12-09 15:45:12,103] {base_hook.py:89} INFO - Using connection to: id: postgres_default. Host: postgres, Port: None, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2020-12-09 15:45:12,187] {taskinstance.py:1150} ERROR - could not translate host name "postgres" to address: nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/hooks/postgres_hook.py", line 93, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2020-12-09 15:45:12,199] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=Write_data_to_PG, task_id=create_table, execution_date=20201209T101000, start_date=20201209T101511, end_date=20201209T101512
[2020-12-09 15:45:16,991] {local_task_job.py:102} INFO - Task exited with return code 1
