[2020-12-05 04:24:45,880] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-04T18:45:00+00:00 [queued]>
[2020-12-05 04:24:45,892] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-04T18:45:00+00:00 [queued]>
[2020-12-05 04:24:45,892] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-05 04:24:45,892] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-05 04:24:45,892] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-05 04:24:45,898] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-04T18:45:00+00:00
[2020-12-05 04:24:45,900] {standard_task_runner.py:54} INFO - Started process 21942 to run task
[2020-12-05 04:24:45,934] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-04T18:45:00+00:00', '--job_id', '48', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpjaup0xe4']
[2020-12-05 04:24:45,936] {standard_task_runner.py:78} INFO - Job 48: Subtask Data_from_table2
[2020-12-05 04:24:45,971] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-04T18:45:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-05 04:24:45,990] {logging_mixin.py:112} INFO - Error::::: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
[2020-12-05 04:24:45,990] {logging_mixin.py:112} INFO - 
[2020-12-05 04:24:45,991] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-05 04:24:45,995] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201204T184500, start_date=20201204T225445, end_date=20201204T225445
[2020-12-05 04:24:50,871] {local_task_job.py:102} INFO - Task exited with return code 0
