[2020-12-16 18:52:09,917] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T13:15:00+00:00 [queued]>
[2020-12-16 18:52:10,050] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T13:15:00+00:00 [queued]>
[2020-12-16 18:52:10,050] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 18:52:10,050] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 18:52:10,051] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 18:52:10,076] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table2> on 2020-12-16T13:15:00+00:00
[2020-12-16 18:52:10,085] {standard_task_runner.py:54} INFO - Started process 3978 to run task
[2020-12-16 18:52:10,187] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table2', '2020-12-16T13:15:00+00:00', '--job_id', '1877', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpoudj_xmo']
[2020-12-16 18:52:10,191] {standard_task_runner.py:78} INFO - Job 1877: Subtask Data_from_table2
[2020-12-16 18:52:10,287] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table2 2020-12-16T13:15:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-16 18:52:10,600] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 18:52:10,601] {logging_mixin.py:112} INFO - 
[2020-12-16 18:52:10,602] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 18:52:10,614] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table2, execution_date=20201216T131500, start_date=20201216T132209, end_date=20201216T132210
[2020-12-16 18:52:14,976] {local_task_job.py:102} INFO - Task exited with return code 0
