[2020-12-16 17:57:34,485] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T12:20:00+00:00 [queued]>
[2020-12-16 17:57:34,658] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T12:20:00+00:00 [queued]>
[2020-12-16 17:57:34,658] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 17:57:34,658] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-16 17:57:34,663] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-16 17:57:34,735] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-16T12:20:00+00:00
[2020-12-16 17:57:34,748] {standard_task_runner.py:54} INFO - Started process 1689 to run task
[2020-12-16 17:57:35,055] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-16T12:20:00+00:00', '--job_id', '1863', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpd49v6ckg']
[2020-12-16 17:57:35,108] {standard_task_runner.py:78} INFO - Job 1863: Subtask Data_from_table1
[2020-12-16 17:57:35,410] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-16T12:20:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-16 17:57:38,137] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-16 17:57:38,150] {logging_mixin.py:112} INFO - 
[2020-12-16 17:57:38,191] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-16 17:57:38,246] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201216T122000, start_date=20201216T122734, end_date=20201216T122738
[2020-12-16 17:57:39,220] {local_task_job.py:102} INFO - Task exited with return code 0
