[2020-11-11 06:58:08,433] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-10T23:00:00+00:00 [queued]>
[2020-11-11 06:58:08,442] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: First_DAG_for_test.read_csv 2020-11-10T23:00:00+00:00 [queued]>
[2020-11-11 06:58:08,442] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-11 06:58:08,443] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-11 06:58:08,443] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-11 06:58:08,448] {taskinstance.py:901} INFO - Executing <Task(BashOperator): read_csv> on 2020-11-10T23:00:00+00:00
[2020-11-11 06:58:08,450] {standard_task_runner.py:54} INFO - Started process 41751 to run task
[2020-11-11 06:58:08,464] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'First_DAG_for_test', 'read_csv', '2020-11-10T23:00:00+00:00', '--job_id', '145', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/sampleDag.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp1wdgof5v']
[2020-11-11 06:58:08,465] {standard_task_runner.py:78} INFO - Job 145: Subtask read_csv
[2020-11-11 06:58:08,492] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: First_DAG_for_test.read_csv 2020-11-10T23:00:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-11-11 06:58:08,508] {bash_operator.py:113} INFO - Tmp dir root location: 
 /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T
[2020-11-11 06:58:08,509] {bash_operator.py:136} INFO - Temporary script location: /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmpw6a14zz8/read_csvg2_9iska
[2020-11-11 06:58:08,509] {bash_operator.py:146} INFO - Running command: /Users/sundarb/Desktop/sampleCSV.conf
[2020-11-11 06:58:08,514] {bash_operator.py:153} INFO - Output:
[2020-11-11 06:58:08,517] {bash_operator.py:157} INFO - /var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/airflowtmpw6a14zz8/read_csvg2_9iska: line 1: /Users/sundarb/Desktop/sampleCSV.conf: Permission denied
[2020-11-11 06:58:08,517] {bash_operator.py:161} INFO - Command exited with return code 126
[2020-11-11 06:58:08,523] {taskinstance.py:1150} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/Documents/anaconda3/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 165, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-11-11 06:58:08,527] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=First_DAG_for_test, task_id=read_csv, execution_date=20201110T230000, start_date=20201111T012808, end_date=20201111T012808
[2020-11-11 06:58:13,436] {local_task_job.py:102} INFO - Task exited with return code 1
