[2020-12-09 10:35:02,683] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T05:00:00+00:00 [queued]>
[2020-12-09 10:35:02,692] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T05:00:00+00:00 [queued]>
[2020-12-09 10:35:02,692] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 10:35:02,692] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-09 10:35:02,692] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-09 10:35:02,698] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-09T05:00:00+00:00
[2020-12-09 10:35:02,700] {standard_task_runner.py:54} INFO - Started process 37961 to run task
[2020-12-09 10:35:02,744] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-09T05:00:00+00:00', '--job_id', '430', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmphi1ixv6a']
[2020-12-09 10:35:02,746] {standard_task_runner.py:78} INFO - Job 430: Subtask Data_from_table1
[2020-12-09 10:35:02,782] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-09T05:00:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-09 10:35:02,813] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-09 10:35:02,813] {logging_mixin.py:112} INFO - 
[2020-12-09 10:35:02,814] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-09 10:35:02,819] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201209T050000, start_date=20201209T050502, end_date=20201209T050502
[2020-12-09 10:35:07,671] {local_task_job.py:102} INFO - Task exited with return code 0
