[2020-12-15 09:45:08,301] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T04:10:00+00:00 [queued]>
[2020-12-15 09:45:08,333] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T04:10:00+00:00 [queued]>
[2020-12-15 09:45:08,333] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 09:45:08,333] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-15 09:45:08,333] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-15 09:45:08,354] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Data_from_table1> on 2020-12-15T04:10:00+00:00
[2020-12-15 09:45:08,360] {standard_task_runner.py:54} INFO - Started process 51972 to run task
[2020-12-15 09:45:08,460] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Airflow_task', 'Data_from_table1', '2020-12-15T04:10:00+00:00', '--job_id', '1478', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/server-elastic.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmpr_ra1g3j']
[2020-12-15 09:45:08,464] {standard_task_runner.py:78} INFO - Job 1478: Subtask Data_from_table1
[2020-12-15 09:45:08,693] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Airflow_task.Data_from_table1 2020-12-15T04:10:00+00:00 [running]> 153.225.168.192.in-addr.arpa
[2020-12-15 09:45:09,459] {logging_mixin.py:112} INFO - Error::::: FATAL:  database "test_aut" does not exist
[2020-12-15 09:45:09,463] {logging_mixin.py:112} INFO - 
[2020-12-15 09:45:09,466] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-15 09:45:09,574] {taskinstance.py:1057} INFO - Marking task as SUCCESS.dag_id=Airflow_task, task_id=Data_from_table1, execution_date=20201215T041000, start_date=20201215T041508, end_date=20201215T041509
[2020-12-15 09:45:15,580] {local_task_job.py:102} INFO - Task exited with return code 0
