[2020-12-10 15:28:16,857] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:35:00+00:00 [queued]>
[2020-12-10 15:28:16,865] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:35:00+00:00 [queued]>
[2020-12-10 15:28:16,866] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 15:28:16,866] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-12-10 15:28:16,866] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-12-10 15:28:16,870] {taskinstance.py:901} INFO - Executing <Task(PostgresOperator): create_table> on 2020-12-10T09:35:00+00:00
[2020-12-10 15:28:16,872] {standard_task_runner.py:54} INFO - Started process 77548 to run task
[2020-12-10 15:28:16,902] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_PG', 'create_table', '2020-12-10T09:35:00+00:00', '--job_id', '657', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/FileSensorDemo.py', '--cfg_path', '/var/folders/x0/npyjyyg15zj3krdkh0pv612w0000gn/T/tmp4n4np0r5']
[2020-12-10 15:28:16,903] {standard_task_runner.py:78} INFO - Job 657: Subtask create_table
[2020-12-10 15:28:16,929] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_PG.create_table 2020-12-10T09:35:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-12-10 15:28:16,947] {postgres_operator.py:62} INFO - Executing: CREATE TABLE sampletable(
            Date text,
            Open text,
            High text,
            Low text,
            Close text
        );
        
[2020-12-10 15:28:16,951] {base_hook.py:89} INFO - Using connection to: id: postgres_default. Host: postgres, Port: None, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2020-12-10 15:28:16,954] {taskinstance.py:1150} ERROR - could not translate host name "postgres" to address: nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/airflow/hooks/postgres_hook.py", line 93, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/sundarb/airflow/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2020-12-10 15:28:16,959] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=Write_data_to_PG, task_id=create_table, execution_date=20201210T093500, start_date=20201210T095816, end_date=20201210T095816
[2020-12-10 15:43:11,696] {local_task_job.py:113} ERROR - Heartbeat time limited exceeded!
